# -*- coding: utf-8 -*-
"""App_task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qxwucw67DoUbwhLsD3CDr1fNzAme9GEp
"""

# -*- coding: utf-8 -*-

"""
Created on Sat Feb 10 20:51:20 2024

@author: rohit
"""

import numpy as np
import pickle
import pandas as pd
import streamlit as st
from PIL import Image

pickle_in = open("svc_classifier.pkl","rb")
svc_classifier=pickle.load(pickle_in)

def welcome():
    return "Welcome All"

def Cluster_predict(T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18):
    prediction =svc_classifier.predict([[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18]])
    print(prediction)
    return prediction






def main():
    st.title("CLASSIFIER PREDICTION")
    html_temp = """
    <div style="background-color:tomato;padding:10px">
    <h2 style="color:white;text-align:center;">Streamlit Classifier-Prediction ML App </h2>
     </div>
    """


    st.markdown(html_temp,unsafe_allow_html=True)
    T1 = st.text_input("T1","Type Here")
    T2 = st.text_input("T2","Type Here")
    T3 = st.text_input("T3","Type Here")
    T4 = st.text_input("T4","Type Here")
    T5 = st.text_input("T5","Type Here")
    T6 = st.text_input("T6","Type Here")
    T7 = st.text_input("T7","Type Here")
    T8 = st.text_input("T8","Type Here")
    T9 = st.text_input("T9","Type Here")
    T10 = st.text_input("T10","Type Here")
    T11 = st.text_input("T11","Type Here")
    T12 = st.text_input("T12","Type Here")
    T13 = st.text_input("T13","Type Here")
    T14 = st.text_input("T14","Type Here")
    T15 = st.text_input("T15","Type Here")
    T16 = st.text_input("T16","Type Here")
    T17 = st.text_input("T17","Type Here")
    T18 = st.text_input("T18","Type Here")
    result=""
    if st.button("Predict"):
        result=Cluster_predict(T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18)
    st.success('The datapoint belongs to the class. {}'.format(result))






if __name__=='__main__':
    main()





